{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "openperouter.fullname" . }}-controller
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - underlays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - underlays/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - underlays/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l2vnis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3vnis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3vnis/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3vnis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3passthroughs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3passthroughs/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - l3passthroughs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - routernodeconfigurationstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - routernodeconfigurationstatuses/finalizers
  verbs:
  - update
- apiGroups:
  - openpe.openperouter.github.io
  resources:
  - routernodeconfigurationstatuses/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.webhook.enabled }}
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - openpe-validating-webhook-configuration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - update
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "openperouter.fullname" . }}-controller
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "openperouter.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "openperouter.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.fullname" . }}-controller
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "openperouter.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ template "openperouter.controller.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "openperouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- range $key, $value := .Values.openperouter.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ template "openperouter.fullname" . }}-controller
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
