resources:
- bases/openpe.openperouter.github.io_underlays.yaml
- bases/openpe.openperouter.github.io_l3vnis.yaml
- bases/openpe.openperouter.github.io_l2vnis.yaml
- bases/openpe.openperouter.github.io_l3passthroughs.yaml
- bases/openpe.openperouter.github.io_routernodeconfigurationstatuses.yaml
